# Generated by Django 5.0.1 on 2024-01-19 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_remove_listing_max_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='listing_image_file',
        ),
        migrations.AlterField(
            model_name='listing',
            name='auction_open',
            field=models.BooleanField(default=True, verbose_name='Auction Concluded'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Listing time'),
        ),
    ]
