# Generated by Django 5.0.1 on 2024-01-23 06:50

import auctions.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_category_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='closing_time',
            field=models.DateTimeField(default=auctions.models.seventytwohours, verbose_name='closingtime'),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Reserve'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.category'),
        ),
    ]
