# Generated by Django 5.0.1 on 2024-01-26 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='auction_open',
            field=models.BooleanField(default=True, verbose_name='Auction Open'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Starting'),
        ),
    ]
