# Generated by Django 5.0.1 on 2024-01-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_starting_bid_listing_current_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sold Price'),
        ),
        migrations.AddField(
            model_name='listing',
            name='starting_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Starting Price'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Current Bid'),
        ),
    ]
