# Generated by Django 5.0.1 on 2024-02-02 22:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_sold_price_listing_starting_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL, verbose_name='following'),
        ),
    ]
