# Generated by Django 5.0.1 on 2024-02-12 11:00

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_listing_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='closing_time',
            field=models.DateTimeField(default=auctions.models.seventytwohours, verbose_name='Closing time'),
        ),
    ]
