# Generated by Django 5.0.1 on 2024-03-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_parent_alter_comment_user_commentlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentlike',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comment Like', 'verbose_name_plural': 'Comment Likes'},
        ),
    ]
